### ISSUE TITLE
Feature Request | Operator | Allow operator-wandb to accept license as a string or as a secretKeyRef

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/operator#18]
Users should be able to specify the license string as a string as is currently supported or as a reference to secret in the cluster.  There may be some benefit to allowing the same key to be used for both, but it probably needs to be a separate field.

It is expected that the user will create this secret outside operator or the chart

If its possible to use the same key, these would be the desired shapes
```
apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  name: wandb
  namespace: default
spec:
  values:
    global:
      license: <LICENSE_STRING>
```

```
apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  name: wandb
  namespace: default
spec:
  values:
    global:
      license:
          name: <SECRET_NAME>
          key: <SECRET_KEY>
```

If that is not reasonable then a new field will work

```
apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  name: wandb
  namespace: default
spec:
  values:
    global:
      licenseSecret:
          name: <SECRET_NAME>
          key: <SECRET_KEY>
```

`licenseSecret` if specified, should take precedence over the string.

I think only the app chart uses the current value to create a secret which is referenced in the deployment.  The secret should be made conditional and the references updated

**Comment by amanpruthi** [comment]
https://github.com/wandb/helm-charts/pull/218

**Comment by vijay-wandb** [comment]
Mounted license as shown below

```
global:
      host: https://wandb-aws.world-iq.com
      license:
        name: "license-secret"
        key: "license"
```


But it results in

![Image](https://github.com/user-attachments/assets/25b931de-b69e-4003-84bf-0aab0105b524)

**Comment by abhinavg6** [comment]
Vijay to retest as per the conversation in the meeting with Eng.

**Comment by abhinavg6** [comment]
@vijay-wandb - Were you able to retest?

**Comment by vijay-wandb** [comment]
@abhinavg6 @velotioaastha 

I used the correct format like this in values.yaml, but it doesn't appear to work

```
  licenseSecret:
       name: license-secret
       key: license
```

I think, secret references are not being properly defined in the Helm chart

It may be have to like this

```
- name: LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.licenseSecret.name }}  
                  key: {{ .Values.global.licenseSecret.key }}  
```

Instead of

```
- name: LICENSE
  valueFrom:
    secretKeyRef:
      name: {{ include "app.fullname" . }}-config
      key: LICENSE
```
